name: Code Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Black Formatter Check
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: qiyu_sso
